export const stocks = [
  "ASIANPAINT.BO", "AXISBANK.BO", "BAJFINANCE.BO",
  "GOOGL", "AMZN", "TSLA", "META", "NVDA", "NFLX",
  "BRK-B", "JPM", "JNJ", "WMT", "PG", "V", "XOM",
  "RELIANCE.BO", "TCS.BO", "INFY.BO", "HDFCBANK.BO", "ICICIBANK.BO",
  "KOTAKBANK.BO", "LT.BO", "ITC.BO", "SBIN.BO", "BHARTIARTL.BO",
  "HCLTECH.BO", "WIPRO.BO", "TITAN.BO", "ULTRACEMCO.BO", "MARUTI.BO",
  "TATAMOTORS.BO", "M&M.BO", "BAJAJFINSV.BO", "SUNPHARMA.BO", "DRREDDY.BO",
  "ONGC.BO", "POWERGRID.BO", "NTPC.BO", "ADANIENT.BO", "ADANIGREEN.BO",
  "CIPLA.BO", "DABUR.BO", "BPCL.BO", "HINDALCO.BO", "GRASIM.BO"
];